[build] 
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.75.1" # from https://alison.rbind.io/post/2019-02-19-hugo-netlify-toml/
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
[context.branch-deploy.environment]
  HUGO_VERSION = "0.75.1" # 

[context.deploy-preview.environment]
  HUGO_VERSION = "0.75.1"
